DISPLAYING THE PREPROCESSED PART_A TENSORS

In [1]:
import torch
from pathlib import Path
import numpy as np

In [2]:
IMG_DIR = Path(r"C:\Users\mahal\OneDrive\Desktop\DL\torch_images_trainA")
GT_DIR  = Path(r"C:\Users\mahal\OneDrive\Desktop\DL\torch_density_trainA")

In [3]:
sample = "IMG_10"
print("Selected Sample:", sample)

Selected Sample: IMG_10


In [4]:
# Load tensors
img_t = torch.load(IMG_DIR / f"{sample}.pt")   # [3, H, W]
gt_t  = torch.load(GT_DIR  / f"{sample}.pt")   # [1, h, w]

In [5]:
# Convert to numpy
img_np = img_t.numpy()
gt_np  = gt_t.numpy()

---------------------- DISPLAY HEADS ----------------------

In [6]:
print("\n=== IMAGE TENSOR SHAPE ===")
print(img_np.shape)


=== IMAGE TENSOR SHAPE ===
(3, 512, 512)


In [7]:
print("\n=== IMAGE TENSOR 2x2 HEAD (for each channel) ===")
print(img_np[:, :5, :5])        # (3, 2, 2)


=== IMAGE TENSOR 2x2 HEAD (for each channel) ===
[[[-1.5014129  -1.1931673  -0.69654936 -0.19993155  0.7590547 ]
  [-1.5527872  -1.2616663  -1.0390445  -0.8677969   0.31381115]
  [-1.6212862  -1.3815396  -1.073294   -0.43967807  0.2966864 ]
  [-1.6384109  -1.4842881  -1.1075436   0.02269024  0.5535577 ]
  [-1.6726604  -1.4157891  -1.1760426  -0.11430778  0.60493195]]

 [[-1.160364   -0.93277305 -0.617647   -0.42507     0.3102242 ]
  [-1.177871   -0.9502801  -0.9502801  -1.0728291  -0.14495796]
  [-1.212885   -1.0203081  -0.91526604 -0.617647   -0.16246496]
  [-1.177871   -1.055322   -0.862745   -0.00490195  0.18767506]
  [-1.265406   -1.0203081  -0.880252   -0.02240895  0.3977592 ]]

 [[-0.74126357 -0.5669716  -0.39267966 -0.41010883  0.09533776]
  [-0.7238344  -0.5321132  -0.7064052  -1.0549891  -0.37525046]
  [-0.67154676 -0.54954237 -0.60182995 -0.5844008  -0.39267966]
  [-0.5844008  -0.5321132  -0.47982562  0.07790857  0.0081918 ]
  [-0.68897593 -0.47982562 -0.4623964   0.13019615

In [8]:
print("\n=== GT TENSOR SHAPE ===")
print(gt_np.shape)


=== GT TENSOR SHAPE ===
(1, 64, 64)


In [9]:
print("\n=== GT TENSOR 2x2 HEAD ===")
print(gt_np[:, :5, :5])         # (1, 2, 2)


=== GT TENSOR 2x2 HEAD ===
[[[0.85170543 1.317878   1.598354   1.408397   1.3178294 ]
  [0.5752023  0.5696288  0.92348915 0.7594477  0.69936323]
  [0.45128363 0.44082937 0.33908808 0.18938568 0.2920851 ]
  [0.1960836  0.20822042 0.06914148 0.0915796  0.17376992]
  [0.15981285 0.46562034 0.590061   0.43220517 0.45522696]]]


In [10]:
print("\nDone.")


Done.
